# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gameGuiTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(864, 505)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 30, 259, 361))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.heightLabel = QtWidgets.QLabel(self.layoutWidget)
        self.heightLabel.setObjectName("heightLabel")
        self.horizontalLayout.addWidget(self.heightLabel)
        self.heightSpinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.heightSpinBox.setObjectName("heightSpinBox")
        self.horizontalLayout.addWidget(self.heightSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widthLabel = QtWidgets.QLabel(self.layoutWidget)
        self.widthLabel.setObjectName("widthLabel")
        self.horizontalLayout_2.addWidget(self.widthLabel)
        self.widthSpinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.widthSpinBox.setObjectName("widthSpinBox")
        self.horizontalLayout_2.addWidget(self.widthSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widthLabel_2 = QtWidgets.QLabel(self.layoutWidget)
        self.widthLabel_2.setObjectName("widthLabel_2")
        self.horizontalLayout_3.addWidget(self.widthLabel_2)
        self.liveLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.liveLineEdit.setObjectName("liveLineEdit")
        self.horizontalLayout_3.addWidget(self.liveLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widthLabel_3 = QtWidgets.QLabel(self.layoutWidget)
        self.widthLabel_3.setObjectName("widthLabel_3")
        self.horizontalLayout_4.addWidget(self.widthLabel_3)
        self.deadLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.deadLineEdit.setObjectName("deadLineEdit")
        self.horizontalLayout_4.addWidget(self.deadLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.speedLabel = QtWidgets.QLabel(self.layoutWidget)
        self.speedLabel.setObjectName("speedLabel")
        self.horizontalLayout_5.addWidget(self.speedLabel)
        self.speedSpinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.speedSpinBox.setProperty("value", 1)
        self.speedSpinBox.setObjectName("speedSpinBox")
        self.horizontalLayout_5.addWidget(self.speedSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.commitPushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.commitPushButton.setObjectName("commitPushButton")
        self.verticalLayout.addWidget(self.commitPushButton)
        self.pausePushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pausePushButton.setObjectName("pausePushButton")
        self.verticalLayout.addWidget(self.pausePushButton)
        self.stopPushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.stopPushButton.setObjectName("stopPushButton")
        self.verticalLayout.addWidget(self.stopPushButton)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(390, 30, 401, 371))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 864, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.heightLabel.setText(_translate("MainWindow", "高度"))
        self.widthLabel.setText(_translate("MainWindow", "宽度"))
        self.widthLabel_2.setText(_translate("MainWindow", "live点规则"))
        self.widthLabel_3.setText(_translate("MainWindow", "dead点规则"))
        self.speedLabel.setText(_translate("MainWindow", "间隔时间"))
        self.commitPushButton.setText(_translate("MainWindow", "确认"))
        self.pausePushButton.setText(_translate("MainWindow", "暂停"))
        self.stopPushButton.setText(_translate("MainWindow", "停止"))

